src/FeatureBundle/Entity/FeatureVersion.php
<?php

namespace FeatureBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * FeatureVersion
 *
 * @ORM\Table(name="feature_version", indexes={@ORM\Index(name="feature", columns={"feature"}),
 * @ORM\Index(name="fk_FV_FR", columns={"request_id"})})
 * @UniqueEntity(fields={"feature", "number"}, message="Версия уже зарегестрирована!")
 * @ORM\Entity
 */
class FeatureVersion {
    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @Assert\Regex(pattern="/^(:?\d+\.?){2,}$/", message="Некорректный формат версии!")
     * @ORM\Column(name="number", type="string", length=255, nullable=false)
     */
    private $number;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \FeatureBundle\Entity\FeatureRequest
     *
     * @ORM\ManyToOne(targetEntity="FeatureBundle\Entity\FeatureRequest")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="request_id", referencedColumnName="id")
     * })
     */
    private $request;

    /**
     * @var \FeatureBundle\Entity\Feature
     *
     * @ORM\ManyToOne(targetEntity="FeatureBundle\Entity\Feature")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="feature", referencedColumnName="id")
     * })
     */
    private $feature;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="FeatureBundle\Entity\Task", mappedBy="featureVersion")
     */
    private $task;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="FeatureBundle\Entity\Bug", mappedBy="featureVersion")
     */
    private $bug;


    /**
     * Constructor
     */
    public function __construct() {
        $this->task = new \Doctrine\Common\Collections\ArrayCollection();
    }


    /**
     * Set description
     *
     * @param string $description
     *
     * @return FeatureVersionStatus
     */
    public function setDescription($description) {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription() {
        return $this->description;
    }

    /**
     * Set number
     *
     * @param string $number
     *
     * @return FeatureVersionStatus
     */
    public function setNumber($number) {
        $this->number = $number;

        return $this;
    }

    /**
     * Get number
     *
     * @return string
     */
    public function getNumber() {
        return $this->number;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set request
     *
     * @param \FeatureBundle\Entity\FeatureRequest $request
     *
     * @return FeatureVersionStatus
     */
    public function setRequest(\FeatureBundle\Entity\FeatureRequest $request = null) {
        $this->request = $request;

        return $this;
    }

    /**
     * Get request
     *
     * @return \FeatureBundle\Entity\FeatureRequest
     */
    public function getRequest() {
        return $this->request;
    }

    /**
     * Set feature
     *
     * @param \FeatureBundle\Entity\Feature $feature
     *
     * @return FeatureVersionStatus
     */
    public function setFeature(\FeatureBundle\Entity\Feature $feature = null) {
        $this->feature = $feature;

        return $this;
    }

    /**
     * Get feature
     *
     * @return \FeatureBundle\Entity\Feature
     */
    public function getFeature() {
        return $this->feature;
    }

    /**
     * Add task
     *
     * @param \FeatureBundle\Entity\Task $task
     *
     * @return FeatureVersionStatus
     */
    public function addTask(\FeatureBundle\Entity\Task $task) {
        $this->task[] = $task;

        return $this;
    }

    /**
     * Remove task
     *
     * @param \FeatureBundle\Entity\Task $task
     */
    public function removeTask(\FeatureBundle\Entity\Task $task) {
        $this->task->removeElement($task);
    }

    /**
     * Get task
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTask() {
        return $this->task;
    } 
    
    /**
     * Add bug
     *
     * @param \FeatureBundle\Entity\Bug $bug
     *
     * @return FeatureVersionStatus
     */
    public function addBug(\FeatureBundle\Entity\Bug $bug) {
        $this->bug[] = $bug;

        return $this;
    }

    /**
     * Remove bug
     *
     * @param \FeatureBundle\Entity\Bug $bug
     */
    public function removeBug(\FeatureBundle\Entity\Bug $bug) {
        $this->bug->removeElement($bug);
    }

    /**
     * Get bug
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getBug() {
        return $this->bug;
    }

    public function getLabel() {
        return $this->feature->getTitle() . ' v.' . $this->number;
    }
}

src/FeatureBundle/Controller/ReportController.php
<?php

namespace FeatureBundle\Controller;

use FeatureBundle\Entity\Product;
use FeatureBundle\Service\FeatureVersionProductVersionStatusChangeService;
use FeatureBundle\Service\FeatureVersionProductVersionStatusService;
//use Sonata\AdminBundle\Controller\CRUDController as Controller;
use FeatureBundle\Service\FeatureVersionStatusService;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

class ReportController extends Controller {

    /**
     * @Route ("/feature_versions_for_product_versions_list", name="feature_versions_for_product_versions_list",
     *        methods={"GET"})
     */
    public function fullListAction() {
        /** @var FeatureVersionProductVersionStatusService $service */
        $service = $this->get('feature.feature_version_product_version_status');
        $list = $service->getFullList();
        return $this->render('FeatureBundle:Admin:report/feature_versions_for_product_versions.html.twig', [
            'list' => $list
        ]);
    }

    /**
     * @Route ("/feature_versions_status_changes_for_product/{product}",
     *        name="feature_versions_status_changes_for_product", methods={"GET"})
     */
    public function statusChangeAction(Product $product) {
        /** @var FeatureVersionStatusService $statusService */
        $statusService  = $this->get('feature.feature_version_status');
        $statusDictionary = $statusService->getAll();

        /** @var FeatureVersionProductVersionStatusChangeService $changesService */
        $changesService = $this->get('feature.feature_version_product_version_status_change');
        $changes = $changesService->getByProduct($product);
        //var_dump($list);
        return $this->render('FeatureBundle:Admin:report/feature_versions_status_changes_for_product.html.twig', [
            'product' => $product,
            'changes' => $changes,
            'statuses' => $statusDictionary
        ]);
    }
}

src/FeatureBundle/Resources/views/Admin/report/feature_versions_for_product_versions.html.twig
{% extends 'SonataAdminBundle::standard_layout.html.twig' %}
        
{% block breadcrumb %}
    <li><a href="{{ url('sonata_admin_dashboard') }}">{% trans %}Dashboard{% endtrans %}</a><span
                class="divider">/</span></li>
    <li class="active">Custom Page</li>
{% endblock %}
    
{% block content %}
    <style>
        table {
            width: 300px;
        }
        td {
            padding: 10px;
        }
    </style>
    {% for productTitle, versions in list %}
        <h1>{{ productTitle|split('|||')[1] }}</h1><a target="_blank"
                                      href="{{ path('feature_versions_status_changes_for_product', {'product' : productTitle|split('|||')[0]}) }}">просмотреть переходы по статусам</a><br>
        {% for productVersionTitle, featureVersions in versions %}
            <h2>{{ productVersionTitle }}</h2><br>
            <table cellpadding="7">
                <thead>
                <tr>
                    <td>Фича</td>
                    <td>Версия</td>
                    <td>Статус</td>
                </tr>
                </thead>
                <tbody>
                {% for version in featureVersions %}
                    <tr>
                        <td><a target="_blank"
                               href="{{ path('admin_feature_feature_edit', {'id' : version.feature_id}) }}">{{ version.feature_name }}</a>
                        </td>
                        <td><a target="_blank"
                               href="{{ path('admin_feature_featureversion_edit', {'id' : version.feature_version_id}) }}">{{ version.feature_version_number }}</a>
                        </td>
                        <td><a target="_blank"
                               href="{{ path('admin_feature_featureversionproductversionstatus_edit', {'id' : version.feature_version_status_id}) }}">{{ version.feature_version_status_name }}</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        {% endfor %}

        <hr>
    {% endfor %}
{% endblock %}

src/FeatureBundle/Resources/views/Admin/report/feature_versions_status_changes_for_product.html.twig
{% extends 'SonataAdminBundle::standard_layout.html.twig' %}
        
{% block breadcrumb %}
    <li><a href="{{ url('sonata_admin_dashboard') }}">{% trans %}Dashboard{% endtrans %}</a><span
                class="divider">/</span></li>
    <li class="active">Custom Page</li>
{% endblock %}
    
{% block content %}
    <style>


        td {
            padding: 10px;
        }
    </style>
    <h1>{{ product.getTitle }}</h1><br>
    {% for productVersionId, productVersionData in changes %}
        <h2><a target="_blank"
               href="{{ path('admin_feature_productversion_edit', {'id' : productVersionId}) }}">{{ productVersionData.label }}</a></h2><br>
        <table>
            <thead>
            <tr>
                <td>Фича</td>
                {% for status in statuses %}
                    <td>{{ status.getName() }}</td>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for featuresVersionId, featuresVersionData in productVersionData.features_versions %}
                <tr>
                    <td><a target="_blank"
                           href="{{ path('admin_feature_featureversion_edit', {'id' : featuresVersionId}) }}">{{ featuresVersionData.label }}</a></td>
                    {% for status in statuses %}

                        <td>{{ featuresVersionData.status_changes[status.getId()] is defined ? featuresVersionData.status_changes[status.getId()]  : ' '  }}</td>

                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <hr>
    {% endfor %}
{% endblock %}